ErlangVMA.Web/Models/LoginModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Security;

namespace ErlangVMA
{
	public class LoginModel
	{
		[Required]
		public string Name
		{
			get;
			set;
		}

		[Required]
		public string Password
		{
			get;
			set;
		}

		[DefaultValue(false)]
		public bool Remember
		{
			get;
			set;
		}
	}
}

ErlangVMA.Web/Models/RegisterModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ErlangVMA
{
    public class RegisterModel
    {
        [Required]
        [Display(Name = "Name")]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }

        [Display(Name = "Confirm password")]
        public string ConfirmPassword { get; set; }
    }
}

ErlangVMA.Web/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;

namespace ErlangVMA.Web.Controllers
{
    public class AuthenticationController : Controller
    {
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View(new LoginModel());
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var userManager = new UserManager<IdentityUser>(new UserStore<IdentityUser>(new IdentityDbContext("VmNodesDbContext")));
                var user = userManager.FindAsync(model.Name, model.Password).Result;

                if (user != null)
                {
                    var authentication = Request.GetOwinContext().Authentication;
                    var identity = userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie).Result;

                    authentication.SignIn(new AuthenticationProperties { IsPersistent = model.Remember }, identity);

                    return Redirect(!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl) ? returnUrl : "/");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "No user with the provided user name and password exists");
                }
            }

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View(new RegisterModel());
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Register(RegisterModel model)
        {
            if (model.Password != model.ConfirmPassword)
            {
                ModelState.AddModelError(string.Empty, "Password confirmation failed");
            }

            if (ModelState.IsValid)
            {
                var userManager = new UserManager<IdentityUser>(new UserStore<IdentityUser>(new IdentityDbContext("VmNodesDbContext")));
                var registration = userManager.CreateAsync(new IdentityUser { UserName = model.UserName }, model.Password).Result;

                if (registration.Succeeded)
                {
                    var authentication = Request.GetOwinContext().Authentication;

                    var user = userManager.FindAsync(model.UserName, model.Password).Result;
                    if (user != null)
                    {
                        var identity = userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie).Result;
                        authentication.SignIn(new AuthenticationProperties { IsPersistent = false }, identity);

                        return Redirect("/");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "No user with the provided user name and password exists");
                    }
                }
                else
                {
                    foreach (string error in registration.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error);
                    }
                }
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut("ApplicationCookie");

            return Redirect("/");
        }
    }
}

ErlangVMA.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

namespace ErlangVMA.Web.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			ViewData["Message"] = "Welcome to ASP.NET MVC on Mono!";
			return View();
		}

		public ActionResult VirtualMachine()
		{
			return View();
		}
	}
}

ErlangVMA.Web/Controllers/VirtualMachineController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using ErlangVMA.VmController;

namespace ErlangVMA.Web.Controllers
{
    [Authorize]
    public class VirtualMachineController : Controller
    {
        private readonly IVmBroker vmBroker;

        public VirtualMachineController(IVmBroker vmBroker)
        {
            this.vmBroker = vmBroker;
        }

        [HttpGet]
        public ActionResult List()
        {
            var virtualMachines = vmBroker.GetVirtualMachines(GetCurrentUser());

            return View(virtualMachines);
        }

        [HttpGet]
        public ActionResult StartNew()
        {
            return View(new VirtualMachineStartOptions());
        }

        [HttpPost]
        public ActionResult StartNew(VirtualMachineStartOptions startOptions)
        {
            var stopwatch = Stopwatch.StartNew();

            if (!ModelState.IsValid)
            {
                return View(startOptions);
            }

            int virtualMachineId = vmBroker.StartNewNode(GetCurrentUser(), startOptions);

            Debug.WriteLine("Starting new virtual machine took {0} ms", stopwatch.ElapsedMilliseconds);

            return RedirectToAction("Interact", new { id = virtualMachineId });
        }

        [HttpGet]
        public ActionResult Interact(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("List");
            }
            return View(id.Value);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Shutdown(int id, string returnUrl)
        {
            vmBroker.ShutdownNode(GetCurrentUser(), id);

            if (!string.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("List");
        }

        private VmUser GetCurrentUser()
        {
            return new VmUser(HttpContext.User.Identity.Name);
        }
    }
}

ErlangVMA.Web/Views/Authentication/Login.cshtml
@model ErlangVMA.LoginModel

<form id="loginForm" method="post">
    <h3>
        Login
    </h3>

    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.Name):
            </td>
            <td>
                @Html.TextBoxFor(model => model.Name, new { @class = "fullwidth" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(model => model.Name)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Password):</td>
            <td>
                @Html.PasswordFor(model => model.Password, new { @class = "fullwidth" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(model => model.Password)</td>
        </tr>
        <tr>
            <td colspan="2">
                <label>
                    @Html.CheckBoxFor(model => model.Remember)
                    Remember me
                </label>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                @Html.ValidationSummary(true)
            </td>
        </tr>
        <tr>
            <td>
                <a href="@Url.Action("Register")">Register</a>
            </td>
            <td>
                <input type="submit" value="Login" name="Login" />
            </td>
        </tr>
    </table>
</form>

ErlangVMA.Web/Views/Authentication/Register.cshtml
@model ErlangVMA.RegisterModel

@{
    ViewBag.Title = "Register";
}

<form id="registerForm" method="post">
    <h3>
        Register
    </h3>

    <table>
        <tr>
            <td>
                @Html.LabelFor(model => model.UserName):
            </td>
            <td>
                @Html.TextBoxFor(model => model.UserName, new { @class = "fullwidth" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(model => model.UserName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Password):</td>
            <td>
                @Html.PasswordFor(model => model.Password, new { @class = "fullwidth" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(model => model.Password)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.ConfirmPassword):</td>
            <td>
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "fullwidth" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(model => model.ConfirmPassword)</td>
        </tr>
        <tr>
            <td colspan="2">
                @Html.ValidationSummary(true)
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Register" name="Register" />
            </td>
        </tr>
    </table>
</form>

ErlangVMA.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<p>
    Welcome to <i>webterm</i>! This site aims to provide remote access and control of Erlang virtual machines.
    All interaction with running Erlang nodes is possible entirely from your web browser.
</p>

ErlangVMA.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        @Styles.Render("~/default")
        @Scripts.Render("~/jquery")
        
        @RenderSection("scripts", false)
    </head>
    <body>
        <div id="upperToolbar">
            <div>
                <div id="links">
                    @Html.ActionLink("List", "List", "VirtualMachine", null, new { @class = "actionlink" })
                    @Html.ActionLink("Start new", "StartNew", "VirtualMachine", null, new { @class = "actionlink" })
                </div>
                <div style="float: right">
                @if (Request.IsAuthenticated)
                {
                    <span>Hello, @Html.Encode(Context.User.Identity.Name)</span>
                    <a href="@Url.Action("Logout", "Authentication")"><b>Logout</b></a>
                }
                else
                {
                    @Html.ActionLink("Register", "Register", "Authentication", null, new { @class = "actionlink" })
                    @Html.ActionLink("Login", "Login", "Authentication", null, new { @class = "actionlink" })
                }
                </div>
                <div style="clear: both"></div>
            </div>
        </div>
        <div id="mainContent">
            @RenderBody()
        </div>
    </body>
</html>

ErlangVMA.Web/Views/VirtualMachine/Interact.cshtml
@model int
@{
    ViewBag.Title = "Interact";
}

@section scripts
{
    <script src="@Url.Content("~/signalr/hubs")" type="text/javascript"></script>
    @Scripts.Render("~/vmconsole")
}

<h2>Interact</h2>

<div id="vmConsole" data-virtual-machine-id="@Model">
    <textarea id="vmConsoleArea" cols="80" rows="24"></textarea>
    <div id="vmConsoleDisplay"></div>
</div>

<div style="float: right">
    <button id="refresh">Refresh</button>
    @using (Html.BeginForm("Shutdown", "VirtualMachine", FormMethod.Post, new { style = "display: inline; margin: 0 10px" } ))
    {
        @Html.Hidden("id", Model)
        <button type="submit">Shutdown</button>
    }
</div>

ErlangVMA.Web/Views/VirtualMachine/List.cshtml
@using ErlangVMA.VmController


@model IEnumerable<VirtualMachine>

<ul>
    @foreach (var vm in Model)
    {
        <li>
            @if (string.IsNullOrEmpty(vm.Name))
            {
                <i>@Html.ActionLink("Unnamed", "Interact", new { id = vm.Id })</i> @: started on @vm.StartedOn on node @vm.NodeAddress@(!vm.IsActive ? " not active" : "")
            }
            else
            {
                @Html.ActionLink(vm.Name, "Interact", new { id = vm.Id }) @: started on @vm.StartedOn on node @vm.NodeAddress@(!vm.IsActive ? " not active" : "")
            }
        </li>
     }
</ul>

ErlangVMA.Web/Views/VirtualMachine/StartNew.cshtml
@using ErlangVMA.VmController
@model VirtualMachineStartOptions

@{
    ViewBag.Title = "Starting of new virtual machine";
}

<h2>Start new virtual machine</h2>
@using(Html.BeginForm())
{
    @Html.EditorForModel()
    
    <button type="submit">Start</button>
}